package dev.cosgy.jmusicbot.slashcommands.owner;

import dev.cosgy.jmusicbot.framework.jdautilities.command.CommandEvent;
import dev.cosgy.jmusicbot.framework.jdautilities.command.SlashCommandEvent;
import dev.cosgy.jmusicbot.framework.jdautilities.commons.JDAUtilitiesInfo;
import com.jagrosh.jmusicbot.Bot;
import com.jagrosh.jmusicbot.utils.OtherUtil;
import com.sedmelluq.discord.lavaplayer.tools.PlayerLibrary;
import dev.cosgy.jmusicbot.slashcommands.OwnerCommand;
import dev.cosgy.jmusicbot.util.DiscordCompat;
import net.dv8tion.jda.api.JDAInfo;
import net.dv8tion.jda.api.Permission;
import net.dv8tion.jda.api.entities.channel.ChannelType;
import net.dv8tion.jda.api.utils.FileUpload;

public class DebugCmd extends OwnerCommand {
    private final static String[] PROPERTIES = {"java.version", "java.vm.name", "java.vm.specification.version",
            "java.runtime.name", "java.runtime.version", "java.specification.version", "os.arch", "os.name"};

    private final Bot bot;

    public DebugCmd(Bot bot) {
        this.bot = bot;
        this.name = "debug";
        this.help = "Displays debug information";
        this.aliases = bot.getConfig().getAliases(this.name);
        this.guildOnly = false;
    }

    @Override
    protected void execute(SlashCommandEvent event) {
        String content = buildDebugInfo(event.getJDA().getSelfUser().getId(), event.getJDA().getGuildCache().size(), event.getJDA().getUserCache().size(), true);
        if (event.isFromGuild() || DiscordCompat.getSelfMember(event.getGuild()).hasPermission(event.getTextChannel(), Permission.MESSAGE_ATTACH_FILES)) {
            event.reply("Debug information").queue();
            event.getChannel().sendFiles(FileUpload.fromData(content.getBytes(), "debug_information.txt")).queue();
            return;
        }
        event.reply("Debug Information: ```\n" + content + "\n```").queue();
    }

    @Override
    protected void execute(CommandEvent event) {
        String content = buildDebugInfo(event.getJDA().getSelfUser().getId(), event.getJDA().getGuildCache().size(), event.getJDA().getUserCache().size(), false);
        if (event.isFromType(ChannelType.PRIVATE)
                || DiscordCompat.getSelfMember(event.getGuild()).hasPermission(event.getTextChannel(), Permission.MESSAGE_ATTACH_FILES))
            event.getChannel().sendFiles(FileUpload.fromData(content.getBytes(), "debug_information.txt")).queue();
        else
            event.reply("Debug Information: ```\n" + content + "\n```");
    }

    private String buildDebugInfo(String selfId, long guildCount, long userCount, boolean includePiiDisclaimer) {
        StringBuilder sb = new StringBuilder();
        sb.append("System Properties:");
        for (String key : PROPERTIES)
            sb.append("\n  ").append(key).append(" = ").append(System.getProperty(key));
        sb.append("\n\nJMusicBot JP Information:")
                .append("\n  Version = ").append(OtherUtil.getCurrentVersion())
                .append("\n  Owner = ").append(bot.getConfig().getOwnerId())
                .append("\n  Prefix = ").append(bot.getConfig().getPrefix())
                .append("\n  AltPrefix = ").append(bot.getConfig().getAltPrefix())
                .append("\n  MaxSeconds = ").append(bot.getConfig().getMaxSeconds())
                .append("\n  NPImages = ").append(bot.getConfig().useNPImages())
                .append("\n  SongInStatus = ").append(bot.getConfig().getSongInStatus())
                .append("\n  StayInChannel = ").append(bot.getConfig().getStay())
                .append("\n  UseEval = ").append(bot.getConfig().useEval())
                .append("\n  UpdateAlerts = ").append(bot.getConfig().useUpdateAlerts());
        sb.append("\n\nDependency Information:")
                .append("\n  JDA Version = ").append(JDAInfo.VERSION)
                .append("\n  JDA-Utilities Version = ").append(JDAUtilitiesInfo.VERSION)
                .append("\n  Lavaplayer Version = ").append(PlayerLibrary.VERSION);
        long total = Runtime.getRuntime().totalMemory() / 1024 / 1024;
        long used = total - (Runtime.getRuntime().freeMemory() / 1024 / 1024);
        sb.append("\n\nRuntime Information:")
                .append("\n  Total Memory = ").append(total)
                .append("\n  Used Memory = ").append(used)
                .append("\n\nDiscord Information:")
                .append("\n  ID = ").append(selfId)
                .append("\n  Guilds = ").append(guildCount)
                .append("\n  Users = ").append(userCount)
                .append("\nPlease do not edit this file if you send it to the developer.");
        if (includePiiDisclaimer)
            sb.append("\nThis file does not contain any personally identifiable information, nor can it be used to hijack accounts.");
        return sb.toString();
    }
}